### PR TITLE
Add Firstory to host list

### PR DESCRIPTION
**Pull request by geniusgordon**

### CODE REVIEW

**Comment by johnspurlock** [comment]
Is there another `pattern` you could use for the media files?

Even through your enclosure urls ultimately redirect to that cloudfront distribution, it is not a pattern present in the rss enclosure url - which I believe is the assumption for every host in this file.  @jamescridland would know for sure

For example, the firstory feed https://open.firstory.me/rss/user/ckv7xwjx56d930814x7v97fbb has
```xml
<enclosure url="https://chrt.fm/track/B62C78/backend.endpoints.firstory-709db.cloud.goog/play.mp3?url=https%3A%2F%2Fstorage.googleapis.com%2Ffirstory-709db.appspot.com%2FRecord%2Fckv7xwjx56d930814x7v97fbb%2F1636044566362.mp3%3Fv%3D1636102092444" length="100566948" type="audio/mpeg"/>
```

`https://chrt.fm/track/B62C78/backend.endpoints.firstory-709db.cloud.goog/play.mp3?url=https%3A%2F%2Fstorage.googleapis.com%2Ffirstory-709db.appspot.com%2FRecord%2Fckv7xwjx56d930814x7v97fbb%2F1636044566362.mp3%3Fv%3D1636102092444`

redirects to 

`https://backend.endpoints.firstory-709db.cloud.goog/play.mp3?url=https%3A%2F%2Fstorage.googleapis.com%2Ffirstory-709db.appspot.com%2FRecord%2Fckv7xwjx56d930814x7v97fbb%2F1636044566362.mp3%3Fv%3D1636102092444`

which redirects to

`https://d3mww1g1pfq2pt.cloudfront.net/Record/ckv7xwjx56d930814x7v97fbb/1636044566362.mp3?v=1636102092444`

**Comment by jamescridland** [comment]
Could we use `endpoints.firststory` ? That looks as if it's likely to be relatively unique.

But I agree, we should be clearer that it's a pattern to look for in the enclosure URL. Thanks, John.  Unlike the user agents list, this list only has raw text and not a regex as a match. At least for now.

**Comment by geniusgordon** [comment]
Oh! I though I need to use the final redirection url. 
I think `endpoints.firstory` is ok for us. I'll update the pr. Thanks!

**Comment by jamescridland** [comment]
Thanks so much!

**Pull request merged**
